### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Ardjlon** [Havoc-OS/android_packages_services_Telephony#4]
https://del.dog/mughyfuvuw.txt

**Comment by rulim34** [comment]
I also experienced the same problem

**Comment by rulim34** [comment]
https://github.com/syberia-project/platform_frameworks_base/commit/f3f3a6ae51e51611265d568e4840a6f3c3b5137a
I think this commit is needed

**Comment by Ardjlon** [comment]
> [syberia-project/platform_frameworks_base@f3f3a6a](https://github.com/syberia-project/platform_frameworks_base/commit/f3f3a6ae51e51611265d568e4840a6f3c3b5137a)
> I think this commit is needed

I will try, thanks

**Comment by Conobi** [comment]
Same issue here
